### ISSUE TITLE
TooMuchData errors

### ISSUE THREAD

**Issue by vbauerster** [LinkTed/doh-client#19]
Hello!

I tried `doh-client` and got following errors:
```
ERROR [doh_client::http2] GetResponse: DNS parser error: TooMuchData
```

**Comment by LinkTed** [comment]
Hi,
this error appears when the DoH server responds with a content bigger than 512 bytes. According to the RFC 1035, a DNS packet has to be 512 bytes or less. Can you tell me which DoH server you use?

**Comment by vbauerster** [comment]
I'm using `unbound` as front forwarding recursive queries to `doh-client` with [a-and-a](https://www.aa.net.uk/legal/dohdot-disclaimer/).

**Comment by LinkTed** [comment]
Can you give me a example DNS request, where this error appears. I use the following argument:
```
doh-client /etc/ca-certificates/extracted/tls-ca-bundle.pem -vv --remote-addr=217.169.20.23:443 --domain dns.aa.net.uk
```

**Comment by vbauerster** [comment]
Unfortunately I can't narrow which query is causing that, but logs suggest apparently all:
[![Screenshot-2019-10-26-at-23-09-12.png](https://i.postimg.cc/FK1dv4sn/Screenshot-2019-10-26-at-23-09-12.png)](https://postimg.cc/kV3XNLSx)

**Comment by LinkTed** [comment]
I add more debug output to the code to get the request and corresponded response. Can you use the fc18f076985a215b926c36de25ec5723e1956f2b commit and use the `-vvv` argument, please?

**Comment by vbauerster** [comment]
[doh-client.log.gz](https://drive.google.com/file/d/1XBTUsFRJW1xmlyi6Re8m9kPdEqBZvi29/view?usp=sharing)

**Comment by LinkTed** [comment]
According to the [RFC 6891](https://tools.ietf.org/html/rfc6891#section-6.2.5) the maximum payload of dns packet, was increased. So i increased the size. Can you test the `doh-client` with the commit 72fad86d66d194bcc00c728a77888fadbe5fc83f and tell me if it works? By the way, if you use `unbound` to cache the dns packet then you should deactivate the cache mechanism of the `doh-client` by using the argument `-c 0`.

**Comment by vbauerster** [comment]
I confirm, that it works now. Thank you for quick fix!
There are [public resolvers](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/public-resolvers.md) with dns stamps available. It would be nice if `doh-client` would support dns stamp format as source for a resolver. For example I had to use [Online DNS Stamp calculator](https://dnscrypt.info/stamps) first, in order to extract domain and ip from a stamp like `sdns://AgcAAAAAAAAADTIxNy4xNjkuMjAuMjIgPhoaD2xT8-l6SS1XCEtbmAcFnuBXqxUFh2_YP9o9uDgNZG5zLmFhLm5ldC51awovZG5zLXF1ZXJ5`.

**Comment by LinkTed** [comment]
Okay, thank you for the reporting.
