### ISSUE TITLE
Question about `not a result of an error`

### ISSUE THREAD

**Issue by vbauerster** [LinkTed/doh-client#21]
Hi!

I use `doh-client` on slow network and it works well, but there are plenty of error messages like:
```
ERROR [doh_client::http2] send_request: protocol error: not a result of an error
```
What does it mean? Is it because of my slow network or something else?

**Comment by LinkTed** [comment]
This means that the server is closing the connection. In the most cases, because there was no request for a long period. I know this error message is very strange, but it comes from the `h2` crate.

**Comment by vbauerster** [comment]
Ok, thank you!
