### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by MarinoMtz** [LinkTed/doh-client#30]
Hi, I'm very interested in using your DoH client, however, I have got a problem when trying to install your software on Linux.

I did everything as suggested in the README file: compile, copying the binary and the config files to the respective locations.

Then when I try to start the service with systemctl sart doh-client, i have this error at the log:

/usr/bin/doh-client: error while loading shared libraries: libgcc_s.so.1: cannot stat shared object: Operation not permitted

Aditional info: 
- cargo 1.51.0
- Ubuntu 18.04.5 LTS
- when i run the command ldconfig -p | grep libgcc_s.so.1; i got this :

marino@marino-PC:~$ ldconfig -p | grep libgcc_s.so.1
	libgcc_s.so.1 (libc6,x32) => /usr/libx32/libgcc_s.so.1
	libgcc_s.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libgcc_s.so.1
	libgcc_s.so.1 (libc6) => /lib/i386-linux-gnu/libgcc_s.so.1
	libgcc_s.so.1 (libc6) => /usr/lib32/libgcc_s.so.1

Do you have any idea why i'm getting this?,

Thank you very much.
Ivan Martinez
IMT Atlantique

**Comment by LinkTed** [comment]
Do you use the `doh-client.service` to start the `doh-client`?

**Comment by MarinoMtz** [comment]
Hi, yes, I did it, and I also tried to start the program directly with the binary file, but still the same error.

However, I also downloaded and compiled the 3.0.0 release and it works fine.

**Comment by LinkTed** [comment]
The system call filters in `doh-client.service` is adjusted for the arch Linux kernel. Therefore, it probably doesn't work for Ubuntu.

So, you compile the v3.0.2 and execute with the following command and did not work?
```bash
$ ./doh-client -l 127.0.0.1:5353
```

**Comment by MarinoMtz** [comment]
Hi, I just tried again in Ubuntu 20 and it seems to work with ./doh-client -l 127.0.0.1:5353, but still noting when using doh-client.service.

Thanks for your help

**Comment by LinkTed** [comment]
Thanks for the info. I will make a commit, where I remove the syscall filter and only add them for Arch Linux. If you directly call the doh-client then you have to specify a port higher than 1024 or run it as root, because the default Port ist 53.

**Comment by LinkTed** [comment]
If it works, would you close this issue?
