### ISSUE TITLE
Use doh client using self signed certificates with doh-client v3.0.0.

### ISSUE THREAD

**Issue by MarinoMtz** [LinkTed/doh-client#31]
Hi, I'm very interested in using your software to setup a private DoH Client.

However, when I try to start your doh client using client-side authentication i've got some problems. 

For that I have:

- A private DoH Server configured with nginx with client side authentication, something like: https://fardog.io/blog/2017/12/30/client-side-certificate-authentication-with-nginx/
- The certificates were created using OpenSSL, therefore there is a CA certificate that I used to sign the server and the client certificates. Then, to execute the DoH client I have : 

sudo ./doh-client /path/to/client/cert.pem -d dns.example.net -r DNSIP:443

- Then I get this error: [ERROR doh_client::remote::session] Could not connect to dns.example.net at DNSIP:443: IO Error: invalid certificate: UnknownIssuer

Additional info:

- I already succeed to connect to my dns server without the client-authentication part so I know my server is working. For that I execute: ./doh-client -d dns.example.net -r DNSIP:443

So my question is: is it possible to do what i'm trying to do with your DoH client?, did I miss something necessary to configure it well?

Thank you very much for your help.

Ivan Martinez.
IMT Atlantique

**Comment by LinkTed** [comment]
Yes, if you have your personally CA cert, you have to tell the `doh-client` do not use the system CA store. Instead, it should use your CA file, by add the filepath of the cert at the end. For example:
```bash
./doh-cllient /path/of/your/ca/file.pem
```

**Comment by MarinoMtz** [comment]
I'm kind of lost, when you say CA cert, is the one I've created to sign the child ones?, or should it be issued by another authority?

**Comment by LinkTed** [comment]
It is the one you have created to sign the other certs.

**Comment by MarinoMtz** [comment]
Hello,

I tried to do it but I'm still getting the same error : 

```[ERROR doh_client::remote::session] Could not connect to dns.example.net at DNSIP:443: IO Error: invalid certificate: UnknownIssuer```

I also tried to merge the certificates by doing ```cat dohclient.cert.pem ca.cert.pem dohclient.key.pem > full_chain.cert.pem``` but still nothing.

I did check that my server is working by sing the openssl commands ```openssl s_client -connect dns.example.net:443 -cert dohclient.cert.pem -key dohclient.key.pem -state -quiet``` and everithing seems to be ok. 

Do you have any idea?, I can also provide you with my actual certs and doh server url/IP so that you can try in your side if you're willing to help me.

Thank you

**Comment by LinkTed** [comment]
Can you execute the following command and tell me what the first line is printed?
```bash
RUST_LOG=DEBUG ./doh-client -l 127.0.0.1:5353
```

It should be something like:
```bash
[DEBUG rustls::anchors] add_pem_file processed 129 valid and 0 invalid certs
```

**Comment by MarinoMtz** [comment]
Hi,

I've got `` [DEBUG rustls::anchors] add_pem_file processed 132 valid and 0 invalid certs ``

I think your software is OK, I was a bit confused about what I can actually do with a DoH client, normally we can't use it to client-authentication, we just pass the argument to a CA certificate. It will be nice though to have authentication in both sides. Maybe a future enhancement?

Thanks

**Comment by LinkTed** [comment]
So you need client cert authentication?

**Comment by MarinoMtz** [comment]
Yes, i'm working on a project where we need to have client-authentication

**Comment by LinkTed** [comment]
Hi @MarinoMtz,
I added a client authentication feature in this commit 66e7fd4e83d86e08ac6a18a91608c7ee208bed9f. Unfortunately, I did not have time yet to test it. Maybe you want to test it.

**Comment by LinkTed** [comment]
I tested it and it worked.
