### ISSUE TITLE
connection error detected: frame with invalid size

### ISSUE THREAD

**Issue by itsTyrion** [LinkTed/doh-client#32]
I'm getting these errors on Fedora 35 with AdGuard Home stable running behind nginx: 
```
[ERROR doh_client::remote::helper] HTTP2 connection close: connection error detected: frame with invalid size
[ERROR doh_client::handler] Could not retrieve DNS response from server: H2 Error: connection error detected: frame with invalid size
[ERROR doh_client::run] Could not handle request: Could not get response for: Dns *debug print of Dns struct*
```
![image](https://user-images.githubusercontent.com/17730120/140794570-04ccd7df-fd90-47f1-800e-b328644dd14c.png)
(I'm using the cache flag to make sure that's not the cause and timeout/retries flags to speed it up until I get it working)

Am I doing this wrong? It works on my iPhone

**Comment by LinkTed** [comment]
Hi @itsTyrion,
It seems the server that doesn't respond with HTTP2 (see [Issue](https://github.com/hyperium/h2/issues/470)). What do you mean with "behind nginx"? Does it mean that you are using a proxy?

**Comment by itsTyrion** [comment]
Sweet. So replying to the GitHub email doesn't actually send a reply, even though it says you can reply.

> Does it mean that you are using a proxy?

Sort of. I reverse proxy everything http(s) on my VPS behind nginx (Gitea, Webmin, Syncthing, AdGuard..) for cert management and to have everything accessible on 443.

So basically, Hyperium H2 just has a confusing error message for "this isn't HTTP 2.0" and I forgot the `http2`.

It now works after I changed
`listen [::]:443 ssl;`
`listen 443 ssl;`
to
`listen [::]:443 http2 ssl;`
`listen 443 http2 ssl;`

Now only this happens, if (and only if) DNSSEC is active in AdGuard Home. Issue on my end, on AGH, expected...?
![image](https://user-images.githubusercontent.com/17730120/141652078-f0a1bf05-d501-456a-b586-812c78c9cf09.png)

**Comment by LinkTed** [comment]
`dns-message-parser` cannot decode the DNS message because the parsing for the type `NSEC` is not yet implemented. If I have time, I will try to implement it. Feel free to open an issue on [`dns-message-parser`](https://github.com/LinkTed/dns-message-parser).
